---
- name: Apply common role to all machines
  hosts: all
  roles:
    - common

- name: Apply workstation role
  hosts: workstations:laptops
  roles:
    - workstation

- name: Apply server role
  hosts: servers
  roles:
    - server

- name: Apply homeserver role
  hosts: homeservers
  roles:
    - homeserver
